import pygame

player_image = pygame.image.load('spriteAssets/player_img.png')
wall_image = pygame.image.load('spriteAssets/wall_img.png')
sign_image = pygame.image.load('spriteAssets/sign.png')
sign_text_intro = pygame.image.load('spriteAssets/sign_text.png')
sign_text_door = pygame.image.load('spriteAssets/sign_text_door.png')
sign_text_door_win = pygame.image.load('spriteAssets/sign_text_door_win.png')
enemy_image = pygame.image.load('spriteAssets/enemy.png')
door_image = pygame.image.load('spriteAssets/door.png')
hpPotion_image = pygame.image.load('spriteAssets/hpPotion.png')
hpPotionIcon_image = pygame.image.load('spriteAssets/hpPotionIcon.png')
dagger_image = pygame.image.load('spriteAssets/dagger.png')
invGrid_image = pygame.image.load('spriteAssets/invGrid.png')
battleMenu_image = pygame.image.load('spriteAssets/battleMenu.png')
gameOver_image = pygame.image.load('spriteAssets/gameOver.png')
cutscene_image = pygame.image.load('spriteAssets/cutscene.png')
portal_img = pygame.image.load('spriteAssets/portal_img.png')
itemSelect_image = pygame.image.load('spriteAssets/itemSelect.png')
cursor_image = pygame.image.load('spriteAssets/cursor.png')
use_image = pygame.image.load('spriteAssets/use.png')

